### ISSUE TITLE
Unable to install picamera library

### ISSUE THREAD

**Issue by shardulkulkarni14** [nsankethreddy/SMART-BIN#4]
How to install picamera library in windows.
I have tried using all the commands available on google but unable to move forward. Can you please help me out with it.

**Comment by nsankethreddy** [comment]
Hey @shardulkulkarni14 this project was made using Linux OS and even the script files for automation were made to be executed on a linux machine/ server. Also all of the contributes/maintainers of this project use Linux as their main OS so I don't think anyone of us can help you with this Windows OS issue.

**Comment by shardulkulkarni14** [comment]
Hey @nsankethreddy, thankyou for your response. I will try to implement this project using linux OS.

**Comment by nsankethreddy** [comment]
All the best. I'll be closing this issue now, feel free to open a new issue if you face any more problems.
